"""CommissionSight — lightweight, zero-dependency Python client for the CommissionSight API.

>>> from commissionsight import CommissionSightClient
>>> cs = CommissionSightClient("https://api.commissionsight.com/v1", token="...")
>>> carriers = cs.list_carriers()
"""

from __future__ import annotations

from .client import CommissionSightClient, Transport, query
from .errors import ApiError
from .types import (
    AdminAccountBilling,
    AdminAccountFile,
    AdminAccountJob,
    AdminAccountOverview,
    AdminAccountUser,
    AdminAlert,
    AdminCronRun,
    AdminCronTask,
    AdminJobDetail,
    AdminLogEvent,
    AdminLogs,
    AdminMetrics,
    AdminProvisionResult,
    AdminRevenueSummary,
    AdminSystemActivity,
    AdminUser,
    AttritionPoint,
    AuditEvent,
    BillingDetails,
    BillingPreview,
    BillingProfile,
    CarrierConfigEntry,
    ChargebackRow,
    ComparisonRow,
    CumulativeCarrier,
    CumulativePeriod,
    CumulativeRange,
    CumulativeReport,
    CumulativeTotals,
    DataQualityReport,
    DataQualitySignal,
    ExpectedCommissionRate,
    FileSummary,
    Flag,
    InferredConfig,
    JobSummary,
    Journey,
    JourneyDelta,
    JourneyPeriod,
    JourneyPolicy,
    Page,
    Pagination,
    ResultRow,
    StabilityLevel,
    Status,
    TeamMember,
    Webhook,
)

__version__ = "0.2.0"

__all__ = [
    "CommissionSightClient",
    "ApiError",
    "Transport",
    "query",
    "__version__",
    # types
    "Status",
    "Flag",
    "StabilityLevel",
    "Page",
    "Pagination",
    "ChargebackRow",
    "JobSummary",
    "FileSummary",
    "ResultRow",
    "ComparisonRow",
    "Journey",
    "JourneyPeriod",
    "JourneyPolicy",
    "JourneyDelta",
    "TeamMember",
    "AuditEvent",
    "BillingDetails",
    "BillingProfile",
    "BillingPreview",
    "ExpectedCommissionRate",
    "Webhook",
    "AttritionPoint",
    "CumulativeReport",
    "CumulativeRange",
    "CumulativeTotals",
    "CumulativePeriod",
    "CumulativeCarrier",
    "DataQualityReport",
    "DataQualitySignal",
    "InferredConfig",
    "CarrierConfigEntry",
    "AdminMetrics",
    "AdminJobDetail",
    "AdminLogEvent",
    "AdminAlert",
    "AdminLogs",
    "AdminAccountOverview",
    "AdminAccountFile",
    "AdminAccountJob",
    "AdminAccountUser",
    "AdminCronRun",
    "AdminCronTask",
    "AdminSystemActivity",
    "AdminRevenueSummary",
    "AdminProvisionResult",
    "AdminAccountBilling",
    "AdminUser",
]
